#!/usr/bin/env python3
"""mkramfs.py ROOTDIR > ramfs_gen.c

Bake a directory tree into a C source file as an in-kernel RAM filesystem, so
the freestanding Larzscript interpreter can fopen()/import files on bare metal.
Paths are emitted rooted at "/" (a flat or nested tree under ROOTDIR)."""
import sys, os

root = sys.argv[1]
files = []
for dirpath, _dirs, names in os.walk(root):
    for n in sorted(names):
        full = os.path.join(dirpath, n)
        rel = "/" + os.path.relpath(full, root).replace(os.sep, "/")
        with open(full, "rb") as f:
            files.append((rel, f.read()))
files.sort()

out = []
out.append("/* generated by mkramfs.py - do not edit */")
out.append("typedef struct { const char *path; const unsigned char *data; unsigned size; } RamFile;")
for i, (rel, data) in enumerate(files):
    body = ",".join(str(b) for b in data)
    out.append("static const unsigned char f%d[] = {%s%s};" % (i, body, ",0" if data else "0"))
out.append("const RamFile g_ramfs[] = {")
for i, (rel, data) in enumerate(files):
    out.append('  {"%s", f%d, %d},' % (rel, i, len(data)))
out.append("};")
out.append("const int g_ramfs_count = %d;" % len(files))
sys.stdout.write("\n".join(out) + "\n")
